#+zola_base_dir: ../../.
#+zola_section: lecture
#+title: Introduction to Environmental Science
#+description: understanding its importance and addressing societal issues.
#+draft: false
#+zola_auto_set_lastmod: t
#+author: Soc Virnyl S. Estela
#+email: socvirnyl.estela@gmail.com
#+date: 2023-07-07
#+zola_lastmod: 2023-07-09

* Definition

Environmental Science is an interdisciplinary field that tackles the importance of the environment
such as forests and marine ecosystems and addressing issues and societal problems that harms the future
of our biosphere.

But before we tackle the subject, let us understand first what is an ecosystem.

* Ecosystems and habitats

These two terms are interchangeable; habitats refer to different levels composition of functional units of
various organisms and abiotic components such as humidity, and may be terrestrial or aquatic. Ecosystems,
however, can encompass from the microscopic level to the entirety of the biosphere. A habitat is, therefore,
just another name for a small part of an ecosystem.

#+begin_quote
  To understand what this means, *the whole planet can be considered an ecosystem as a whole*. A pile of rotten
  logs is also an ecosystem. Habitats are just subjective terms to identify various differences in geographical components
  just like how we name things in general.
#+end_quote

** Components of an ecosystem

An ecosystem is composed of two major parts: _Abiotic Components_ and _Biotic Components_. These components interact with
each other with varying results. The goal is to achieve a more stable system through trial and error.

Ecosystems work in a way that each component has a /*role*/. The environment forces these components with assigned
roles usually in a form of evolutionary features in biotic components and physical barriers e.g. cliffs and rivers.

- Biotic components are organisms or life such as mosquitoes and humans.

- Abiotic components are geological features and components in an ecosystem e.g. minerals and water.

* Energy Flow in the ecosystem

*Energy* is the whole driving force for everything that is happening in or on the planet. Life requires energy to do various functions
where the end goal is to reproduce and to sustain a stable population.

Simplified models of how energy flows in the ecosystem are presented as *energy pyramids*, *food/energy chain*, and the *food web*.
All of these models contain the same or similar components in the following:

- Producers; where composed of autotrophic organisms such as plants.
- Consumers; where these can be further broken down as
  - Primary consumers
  - Secondary consumers
  - Tertiary consumers
- Decomposers; mostly comprised of microorganisms such as fungi and bacteria which breakdown dead matter into simpler compounds.

The model explains in a manner where energy flows from *high density* to *low density*.

** Flaws of these models

Unfortunately, these models do not really explain much of how the ecosystems *actually work*. For example, where can we assign
organisms that generate energy from inorganic sources such as sulfur and methane and not directly from the Sun? These models
fail to actually account for anything *beyond* photosynthesis, herbivory, carnivory, and omnivory.

* Biodiversity

As the words literally means "life in variety" or "life in diversity", biodiversity refers to the *level of desirable /variety/*
of organisms living in an area. These areas can be any habitat from forest ecosystems to a small pond. Before we can see the importance
of biodiversity, let's understand first what is an *ecological niche* or *niche*.

** Ecological Niche

You should read the whole article that describes niches in National Geographic's [[https://education.nationalgeographic.org/resource/niche/][Niche encyclopedic entry]],

#+begin_quote
A species' niche is all of the environment factors and interspecies
relationships that influence the species.
#+end_quote

Species are assigned from their environment for what roles they have. These assignments are either *specialists*
and *generalists*; the former is a result of narrow and limited niches and the latter is a result of broader niches.

#+begin_quote
No two species can have the same exact same niche.
#+end_quote

Otherwise, one species may outcompete over the other for resources and space and may lead the other to extinction or moving
to another area where competition is less.

In other words, each species have designated roles in their habitat because of environmental factors. These designated roles
decides the fate of different species in that ecosystem. A loss of a species may cause an imbalance of roles and cause
a resources shift because of lack of competition or the increase thereof.

** Three levels of biodiversity

There are three levels of biodiversity which focuses on specific aspects as per their names.

*** Genetic Diversity

PLACEHOLDER

*** Species Diversity

PLACEHOLDER

*** Ecosystem diversity

PLACEHOLDER

** Niches and Biodiversity

According to [[https://faculty.washington.edu/jhrl/Levine&HRL09.pdf][Levine and HilleRisLambers (2009)]],

#+begin_quote
Niches are important in maintaining species diversity
#+end_quote


* Offtopic: The Scientific Method

What is the scientific method?

The scientific method is a systematic process of getting the answer or closest answer to a phenomenon or a problem. It starts with

1) *Observation*, it does not necessarily mean you should actually observe. Sometimes it happens in front of you and then you do a;
2) *Hypothesis*, where which you form a statement or an "educated guess" using existing facts and information you gathered to create the possible closest explanation to a phenomena and then do an; 
3) *Experimentation*, where which you formulate a method that is *reproducible* and applies your hypothesis to answer your question. Finally you will reach the;
4) *Conclusion*. However, the conclusion may not give you the exact answer to your question or you may have used the wrong methodology. Sometimes, it gives you more questions than answers.

* Review Questions

1. What is an ecosystem?
2. What are examples of an ecosystem?
3. What are its components? How do they interact with each other?
4. Ecosystems are not static/stagnant. Why is this so?
5. Why are ecosystems important?
6. What is biodiversity? How is biodiversity related to ecosystems?
7. How can biodiversity an indicator of a healthy ecosystem?
8. What are threats to an ecosystem?
9. What are invasive species? Why is an introduction of a species not native to its habitat can be a disaster?
10. Why is the circulation of nutrients in an ecosystem important?

