matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  publish:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    secrets: [ PAGES_ACCESS_TOKEN, MAIL ]
    commands:
      - zypper --non-interactive install just zola git
      - git config --global init.defaultBranch main
      - git config --global user.name "${CI_REPO_OWNER}"
      - git config --global user.email "${MAIL}"
      - just publish
branches:
  include: [ deploy-branch ]
  exclude: [ main, feature/* ]
runs_on: [ success, failure ]
