labels:
  platform: linux/amd64

steps:
  publish:
    when:
      event: [push, tag]
      branch: deploy-branch
    image: opensuse/tumbleweed:latest
    environment:
    commands:
      - zypper --non-interactive install just zola git rsync openssh
      - git config --global init.defaultBranch main
      - git config --global user.name "${CI_REPO_OWNER}"
      - git config --global user.email "${MAIL}"
      - mkdir -p ~/.ssh
      - install -m 600 -D /dev/nul ~/.ssh/id_private
      - echo "$${HASHES}" > ~/.ssh/id_private
      - ssh-keyscan -H "$${TARGET_SOURCE}" > ~/.ssh/known_hosts
      - just publish
    secrets: [ user2, target_source, remote_outpath, mail, hashes]
runs_on: [ success, failure ]
