matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  publish:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    secrets: [ PAGES_ACCESS_TOKEN ]
    commands:
      - zypper --non-interactive install just zola git
      - just publish
branches:
  include: [ deploy-branch ]
  exclude: [ main, feature/* ]
runs_on: [ success, failure ]
