#+zola_base_dir: ../../.
#+zola_section: blog
#+filetags: social fediverse
#+title: Not Threads, Not Twitter. Come Join Us!
#+author: Soc Virnyl Estela
#+description: The Fediverse is growing. Join now!
#+email: socvirnyl.estela@gmail.com
#+date: 2023-07-18

The Fediverse is growing. Joining the Fediverse is good. But *I do not recommend you joining /Threads/,
or go back to /Twitter/*. 

* Not Threads, Not Twitter

Twitter is self-explanatory. Threads, however, are new platforms that support [[https://www.w3.org/TR/activitypub/][ActivityPub]]. This means it can
communicate with other platforms that also support this /protocol/ e.g. you can follow people from your instance
to someone who is on Threads.

But *Threads is owned by Meta*, who are notorious for their aggressive data collection and poor privacy protection
and policies. And they are also known for manipulating public information, and spreading propaganda to accommodate
personal interests from politics to mass misinformation.

/Why should you join a platform who is backed by a company
known for such practices/?

You may have your reasons. It maybe valid e.g. because your fam uses Facebook, specifically, Facebook Messenger to
communicate, but if you have the option to do so, do so now. These companies do not care much about your well-being
since they designed these platform for clout-chasing, dopamine addiction, and a new culture of attention-seekers
that are dumb to a point.

* Come Join the Fediverse!

The fediverse is good.


